### ISSUE TITLE
Converting indented comments

### ISSUE THREAD

**Issue by Pitirus** [dfm/black_nbconvert#2]
When you comment lines of code in Jupyter using a keyboard shortcut the `#` gets added at the beginning of the line instead of the beginning of indent, e.g.:
```python
if True:
    print("not commented")
#    print("commented in Jupyter")
    # print("commented in .py file e.g. in PyCharm")
```
Then after we format it with *black_nbconvert* it looks like following:
```python
if True:
    print("not commented")
    #    print("commented in Jupyter")
    # print("commented in .py file e.g. in PyCharm")
```

Maybe a better approach would be to check if there is more than 1 space between `#` and the start of comment text and then first take those spaces out before the `#` and add a single space between `#` and the start of comment text.

**Comment by dfm** [comment]
Thanks!

I don't think we would want to do something like that in this project, because its a *very* lightweight wrapper of black. Some editors also have the same behavior and applying black to those scripts would produce the same problematic results. But, you could also end up in situations where you *don't* want the solution that you propose (e.g.):

```python
# for i in range(10):
#     print(i)
```

I think that supporting all the possible use cases is beyond the scope here, but you could open a feature request on one of the Jupyter repos (to change the notebook behavior) or on black (to add the feature that you're suggesting here).
